"""
fetch_best_config.py

Reads the best sweep trial from W&B and writes a ready-to-use training config.

After your W&B sweep finishes, run this once:

    python scripts/fetch_best_config.py --sweep-id <sweep_id>

It will:
  1. Connect to W&B and find the best-scoring trial in the sweep
  2. Extract its hyperparameters
  3. Merge them into the base training config (qlora_sft.yaml)
  4. Write the result to configs/train/best_sweep_config.yaml
  5. Upload the config to GCS so the training container can read it
     without requiring an image rebuild

Then submit full training (no image rebuild needed):

    python gcp/pipelines/submit_training_pipeline.py \\
        --train-config /gcs/automend-model2/configs/train/best_sweep_config.yaml
"""

from __future__ import annotations
import argparse
import sys
from pathlib import Path

import yaml
from dotenv import load_dotenv
from loguru import logger

_M2_ROOT       = Path(__file__).resolve().parent.parent
_AUTOMEND_ROOT = _M2_ROOT.parent
sys.path.insert(0, str(_AUTOMEND_ROOT))

load_dotenv(_AUTOMEND_ROOT / ".env")

_BASE_TRAIN_CONFIG = _M2_ROOT / "configs/train/qlora_sft.yaml"
_OUTPUT_CONFIG     = _M2_ROOT / "configs/train/best_sweep_config.yaml"

# GCS — config is uploaded here so the container can read it via FUSE
# without requiring an image rebuild
_GCS_BUCKET        = "automend-model2"
_GCS_CONFIG_PREFIX = "configs/train"

# Keys that live in train config and can be overridden by sweep results
_TRAIN_KEYS = {
    "learning_rate",
    "num_train_epochs",
    "per_device_train_batch_size",
    "gradient_accumulation_steps",
    "lr_scheduler_type",
    "warmup_ratio",
    "weight_decay",
    "lora_r",
    "lora_alpha",
    "lora_dropout",
}

# The metric used as the sweep objective (must match wandb_sweep.yaml)
_OBJECTIVE_METRIC = "benchmark/tax_valid_rate"


def fetch_best_run(sweep_path: str):
    """
    Fetch the best run from a W&B sweep.

    Args:
        sweep_path: Full W&B sweep path: entity/project/sweep_id
                    e.g. mlops-team-northeastern-university/automend-model2/ltilnti3

    Returns:
        (best_run, best_score) tuple.
    """
    try:
        import wandb
    except ImportError:
        logger.error("wandb not installed. Run: pip install wandb")
        sys.exit(1)

    api = wandb.Api()

    logger.info(f"Fetching sweep: {sweep_path}")
    sweep = api.sweep(sweep_path)

    runs = list(sweep.runs)
    if not runs:
        logger.error("No runs found in this sweep.")
        sys.exit(1)

    logger.info(f"Found {len(runs)} completed runs in sweep")

    # Sort by objective metric descending — best run first
    def _score(run) -> float:
        return run.summary.get(_OBJECTIVE_METRIC, -1.0)

    ranked = sorted(runs, key=_score, reverse=True)
    best   = ranked[0]
    score  = _score(best)

    logger.info(f"Best run  : {best.name}")
    logger.info(f"Best score: {_OBJECTIVE_METRIC} = {score:.4f}")

    return best, score


def build_best_config(best_run) -> dict:
    """
    Merge the best run's hyperparameters into the base training config.

    Args:
        best_run: W&B Run object from the sweep.

    Returns:
        Merged config dict ready to save as YAML.
    """
    # Load base config
    with open(_BASE_TRAIN_CONFIG) as f:
        base_cfg = yaml.safe_load(f)

    sweep_params = dict(best_run.config)

    logger.info("Applying sweep overrides:")
    applied = {}
    for key in _TRAIN_KEYS:
        if key in sweep_params:
            old = base_cfg.get(key, "—")
            base_cfg[key] = sweep_params[key]
            applied[key]  = sweep_params[key]
            logger.info(f"  {key}: {old} → {sweep_params[key]}")

    if not applied:
        logger.warning("No sweep parameters matched known train config keys.")

    return base_cfg


def save_config(cfg: dict, output_path: Path, best_run, score: float) -> None:
    """Write config to YAML with a header showing where it came from."""
    header = (
        f"# Auto-generated by fetch_best_config.py\n"
        f"# Source sweep run : {best_run.name}\n"
        f"# W&B run URL      : {best_run.url}\n"
        f"# {_OBJECTIVE_METRIC} : {score:.4f}\n"
        f"#\n"
        f"# To train with this config:\n"
        f"#   python scripts/run_train.py \\\n"
        f"#       --data-config  configs/data/track_b_chatml.yaml \\\n"
        f"#       --model-config configs/model/qwen_baseline.yaml \\\n"
        f"#       --train-config configs/train/best_sweep_config.yaml\n"
        f"#\n"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)

    logger.success(f"Best config saved → {output_path}")


def upload_to_gcs(local_path: Path) -> str:
    """
    Upload config YAML to GCS so the training container can read it
    via the GCS FUSE mount without requiring an image rebuild.

    Returns:
        gs:// URI of the uploaded file, or "" on failure.
    """
    try:
        from google.cloud import storage
    except ImportError:
        logger.warning("google-cloud-storage not installed — skipping GCS upload.")
        return ""

    blob_name = f"{_GCS_CONFIG_PREFIX}/{local_path.name}"
    gcs_uri   = f"gs://{_GCS_BUCKET}/{blob_name}"

    try:
        client = storage.Client()
        bucket = client.bucket(_GCS_BUCKET)
        blob   = bucket.blob(blob_name)
        blob.upload_from_filename(str(local_path))
        logger.success(f"Config uploaded to GCS → {gcs_uri}")
    except Exception as exc:
        logger.warning(f"GCS upload failed ({exc}) — image rebuild will be required.")
        return ""

    return gcs_uri


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch best W&B sweep trial and write a training config."
    )
    parser.add_argument(
        "--sweep-id",
        required=True,
        help=(
            "Full W&B sweep path: entity/project/sweep_id\n"
            "e.g. mlops-team-northeastern-university/automend-model2/ltilnti3\n"
            "Find it on wandb.ai under your project → Sweeps tab."
        ),
    )
    parser.add_argument(
        "--output",
        default=str(_OUTPUT_CONFIG),
        help=f"Where to write the config YAML (default: {_OUTPUT_CONFIG})",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = Path(args.output)

    # Fetch best run from W&B
    best_run, score = fetch_best_run(args.sweep_id)

    # Merge into base config
    best_cfg = build_best_config(best_run)

    # Save locally
    save_config(best_cfg, output_path, best_run, score)

    # Upload to GCS so the container reads it via FUSE (no image rebuild needed)
    gcs_uri = upload_to_gcs(output_path)

    # Print next step
    logger.info("")
    if gcs_uri:
        fuse_path = gcs_uri.replace(f"gs://{_GCS_BUCKET}", f"/gcs/{_GCS_BUCKET}")
        logger.info("Next step — submit full training pipeline (no image rebuild needed):")
        logger.info(
            f"  python gcp/pipelines/submit_training_pipeline.py \\\n"
            f"         --train-config {fuse_path}"
        )
    else:
        logger.info("Next steps — GCS upload failed, rebuild image first:")
        logger.info("  1. bash gcp/build_and_push.sh")
        logger.info(
            f"  2. python gcp/pipelines/submit_training_pipeline.py \\\n"
            f"         --train-config {output_path.name}"
        )


if __name__ == "__main__":
    main()
